language: csharp
os:
  - linux
  - osx
dist: trusty
sudo: required
mono:
  - latest
dotnet: 1.0.1
script:
  - dotnet restore ./src/Draw2D.Core
  - dotnet build ./src/Draw2D.Core/Draw2D.Core.csproj
  - dotnet restore ./src/Draw2D.NetCore
  - dotnet build ./src/Draw2D.NetCore/Draw2D.NetCore.csproj
  - dotnet publish ./src/Draw2D.NetCore/Draw2D.NetCore.csproj -c Release -r ubuntu.14.04-x64 -o bin/ubuntu.14.04-x64
