version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: Core2D.Experimental.sln
  verbosity: minimal
after_build:
- ps: .\NetCore-Build.ps1
- ps: .\NetCore-Publish.ps1
- cmd: NetCore-Patch.cmd
test: off
artifacts:
- path: src\Core2D.Wpf\bin\Release\AnyCPU
  name: Core2D.Wpf-build$(appveyor_build_version)
- path: src\Core2D.Avalonia\bin\win7-x64
  name: Core2D.Avalonia-win7-x64-build$(appveyor_build_version)
- path: src\Core2D.Avalonia\bin\win7-x86
  name: Core2D.Avalonia-win7-x86-build$(appveyor_build_version)
- path: src\Core2D.Avalonia\bin\ubuntu.14.04-x64
  name: Core2D.Avalonia-ubuntu.14.04-x64-build$(appveyor_build_version)
- path: src\Core2D.Avalonia\bin\ubuntu.16.10-x64
  name: Core2D.Avalonia-ubuntu.16.10-x64-build$(appveyor_build_version)
- path: src\Core2D.Avalonia\bin\osx.10.12-x64
  name: Core2D.Avalonia-osx.10.12-x64-build$(appveyor_build_version)
deploy: off
