version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- ps: .\build.ps1
- cmd: patch.cmd
test: off
artifacts:
- path: src\Core2D.Avalonia\bin\win7-x64
  name: Core2D.Avalonia-win7-x64-build$(appveyor_build_version)
deploy: off
