version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: Draw2D.sln
  verbosity: minimal
test: off
artifacts:
- path: src\Draw2D.Wpf\bin\Release
  name: Draw2D.Wpf-build$(appveyor_build_version)
deploy: off
