version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: cd Draw2D/src/Draw2D.NetCore
      - run: dotnet restore
      - run: dotnet build
